# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('webpage_url', models.URLField(blank=True, max_length=255)),
                ('meetup_url', models.URLField(blank=True, max_length=255)),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to=b'uploads/usergroups/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
