# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 18:52


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0002_usergroup_representatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='representatives',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
