# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 07:21


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0007_paperapplication_extra_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usergroups', '0003_auto_20160904_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usergroup_votes', to='cfp.PaperApplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usergroup_votes', to=settings.AUTH_USER_MODEL)),
                ('usergroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='usergroups.UserGroup')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'usergroup', 'application')]),
        ),
    ]
