# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0005_voteaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='uploads/usergroups/'),
        ),
    ]
