# Generated by Django 2.0.4 on 2018-04-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usergroups', '0006_auto_20170519_0944'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='application',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='usergroup',
        ),
        migrations.RemoveField(
            model_name='voteaudit',
            name='application',
        ),
        migrations.RemoveField(
            model_name='voteaudit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='voteaudit',
            name='usergroup',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.DeleteModel(
            name='VoteAudit',
        ),
    ]
