# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 09:12


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0005_auto_20160507_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=1024)),
                ('tagline', models.TextField(blank=True)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=1024)),
                ('code', models.CharField(max_length=1024)),
                ('first_name', models.CharField(max_length=1024)),
                ('last_name', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=1024)),
                ('country', models.CharField(max_length=2)),
                ('company', models.CharField(blank=True, max_length=1024)),
                ('promo_code', models.CharField(blank=True, max_length=1024)),
                ('twitter', models.CharField(blank=True, max_length=1024)),
                ('dietary_preferences', models.CharField(blank=True, max_length=1024)),
                ('purchased_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('tshirt_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.TShirtSize')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set([('event', 'code')]),
        ),
    ]
