# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-08 09:08


from django.db import migrations
from django.core import serializers
from os.path import abspath, join, dirname


def load_fixture(file_path):
    with open(file_path, 'rb') as fixture:
        objects = serializers.deserialize('json', fixture, ignorenonexistent=True)
        for obj in objects:
            obj.save()
        fixture.close()


def load(apps, schema_editor):
    path = abspath(join(dirname(__file__), '../fixtures/initial_data.json'))
    load_fixture(path)


def unload(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Event.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load, unload)
    ]
