# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20161008_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dates_text',
            field=models.CharField(default='6th & 7th October 2017', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='extended_title',
            field=models.CharField(default='WebCamp Zagreb Conference', max_length=1024),
            preserve_default=False,
        ),
    ]
