# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170516_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='invite_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
