# Generated by Django 2.1.8 on 2019-09-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180427_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
