# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='Zagreb, Croatia', max_length=255),
        ),
    ]
