# Generated by Django 2.0.4 on 2018-04-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='text',
            field=models.TextField(),
        ),
    ]
