# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=1024)),
                ('code', models.CharField(max_length=1024)),
                ('first_name', models.CharField(max_length=1024)),
                ('last_name', models.CharField(max_length=1024)),
                ('email', models.CharField(max_length=1024)),
                ('country', models.CharField(max_length=2)),
                ('company', models.CharField(blank=True, max_length=1024)),
                ('promo_code', models.CharField(blank=True, max_length=1024)),
                ('twitter', models.CharField(blank=True, max_length=1024)),
                ('dietary_preferences', models.CharField(blank=True, max_length=1024)),
                ('purchased_at', models.DateTimeField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set([('conference', 'code')]),
        ),
    ]
