# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 08:30
from __future__ import unicode_literals

from django.db import migrations


def link_tickets_to_users(apps, schema_editor):
    Ticket = apps.get_model('conferences', 'Ticket')
    User = apps.get_model('people', 'User')

    for ticket in Ticket.objects.all():
        user = User.objects.filter(email=ticket.email).first()
        if user:
            print "linking %r to %r" % (ticket, user)
            ticket.user = user
            ticket.save()


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_ticket_user'),
    ]

    operations = [
        migrations.RunPython(link_tickets_to_users)
    ]
