# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-30 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20160507_1207'),
        ('conferences', '0004_link_tickets_to_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tshirt_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='people.TShirtSize'),
        ),
    ]
