# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-10 14:43


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0007_paperapplication_extra_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paperapplication',
            options={'ordering': ['title']},
        ),
    ]
