# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0009_callforpaper_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperapplication',
            name='accomodation_required',
            field=models.BooleanField(default=False, help_text='For people outside of the Zagreb area, we provide 2 nights in a hotel.', verbose_name='I require accomodation'),
        ),
        migrations.AlterField(
            model_name='paperapplication',
            name='duration',
            field=models.CharField(choices=[('25', '25 Minutes'), ('45', '45 Minutes')], default='25', help_text='What talk duration slot would you like?', max_length=255, verbose_name='Talk Duration Slot'),
        ),
        migrations.AlterField(
            model_name='paperapplication',
            name='extra_info',
            field=models.TextField(blank=True, help_text='Anything else that you would like to let us know?', null=True, verbose_name='Extra info'),
        ),
    ]
