# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0010_auto_20170519_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='speaker_experience',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paperapplication',
            name='about',
            field=models.TextField(help_text='Describe your talk in 140 characters or less. [Public]', verbose_name="What's it about"),
        ),
        migrations.AlterField(
            model_name='paperapplication',
            name='abstract',
            field=models.TextField(help_text='You may go in more depth here. Up to 10 sentnces, please. [Public]', verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='paperapplication',
            name='skill_level',
            field=models.ForeignKey(help_text='Which skill level is this talk most appropriate for? [Public]', on_delete=django.db.models.deletion.CASCADE, to='cfp.AudienceSkillLevel', verbose_name='Audience level'),
        ),
        migrations.AlterField(
            model_name='paperapplication',
            name='title',
            field=models.CharField(help_text='The title of your talk. Keep it short and catchy. [Public]', max_length=255, verbose_name='Title'),
        ),
    ]
