# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0011_auto_20170523_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperapplication',
            name='about',
            field=models.TextField(help_text='Describe your talk in 140 characters or less. Plain text only. [Public]', verbose_name="What's it about"),
        ),
        migrations.AlterField(
            model_name='paperapplication',
            name='abstract',
            field=models.TextField(help_text='You may go in more depth here. Up to 10 sentnces, use Markdown. [Public]', verbose_name='Abstract'),
        ),
    ]
