# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0012_auto_20170523_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperapplication',
            name='about',
            field=models.TextField(help_text='Describe your talk in 140 characters or fewer. Plain text only. [Public]', max_length=140, verbose_name="What's it about"),
        ),
    ]
