# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0014_auto_20170605_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='company_name',
            field=models.CharField(blank=True, help_text='Name of the company you work for. Optional.', max_length=100),
        ),
    ]
