# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0016_auto_20170620_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='biography',
            field=models.TextField(help_text='Who are you? Where have you worked? What are your professional interests? Up to 10 sentences, use Markdown but avoid headings. [Public]', verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='speaker_experience',
            field=models.TextField(blank=True, help_text="If you've given talks at other events, please list them.Videos which show your english speaking skills are very helpful. Use Markdown but avoid headings.", verbose_name='Speaker experience'),
        ),
        migrations.AlterField(
            model_name='paperapplication',
            name='abstract',
            field=models.TextField(help_text='You may go in more depth here. Up to 10 sentences, use Markdown but avoid headings. [Public]', verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='paperapplication',
            name='accomodation_required',
            field=models.BooleanField(default=False, help_text='For people outside of the Zagreb area, we provide 3 nights in a hotel.', verbose_name='I require accommodation'),
        ),
    ]
