# Generated by Django 2.0.4 on 2018-04-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0017_auto_20170704_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callforpaper',
            name='announcement',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callforpaper',
            name='description',
            field=models.TextField(),
        ),
    ]
