# Generated by Django 2.0.4 on 2018-05-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0018_auto_20180417_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperapplication',
            name='extra_info',
            field=models.TextField(blank=True, default='', help_text='Anything else that you would like to let us know?', verbose_name='Extra info'),
            preserve_default=False,
        ),
    ]
