# Generated by Django 2.0.4 on 2018-05-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0020_auto_20180507_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperapplication',
            name='grant_email_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paperapplication',
            name='grant_process_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paperapplication',
            name='grant_publish_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paperapplication',
            name='grant_publish_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paperapplication',
            name='duration',
            field=models.CharField(choices=[('25', '25 Minutes'), ('45', '45 Minutes')], default='25', help_text='What talk duration slot would you like?  Take into account that there are only 8 slots for 45 minute talks, and 20 slots for 25 minute talks.', max_length=255, verbose_name='Talk Duration Slot'),
        ),
    ]
