# Generated by Django 2.1.7 on 2019-04-02 08:41

from django.db import migrations, models


def migrate_application_type(apps, schema_editor):
    PaperApplication = apps.get_model("cfp", "PaperApplication")
    PaperApplication.objects.filter(duration="25").update(type="talk_short")
    PaperApplication.objects.filter(duration="45").update(type="talk_long")
    PaperApplication.objects.filter(talk__keynote=True).update(type="keynote")


def update_keynote_duration(apps, schema_editor):
    Talk = apps.get_model("talks", "Talk")
    Talk.objects.filter(keynote=True).update(duration="60")


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0022_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperapplication',
            name='type',
            field=models.CharField(choices=[('talk_short', 'Short talk (25 minutes)'), ('talk_long', 'Long talk (45 minutes)'), ('keynote', 'Keynote (60 minutes)'), ('workshop_half', 'Workshop (half day)'), ('workshop_full', 'Workshop (full day)')], default='talk_short', max_length=50, verbose_name='Application Type'),
        ),
        migrations.AlterField(
            model_name='paperapplication',
            name='duration',
            field=models.CharField(blank=True, choices=[('25', '25 Minutes'), ('45', '45 Minutes'), ('60', '60 Minutes')], help_text='What talk duration slot would you like?  Take into account that there are only 8 slots for 45 minute talks, and 20 slots for 25 minute talks.', max_length=255, null=True, verbose_name='Talk Duration Slot'),
        ),
        migrations.RunPython(migrate_application_type, migrations.RunPython.noop),
        migrations.RunPython(update_keynote_duration, migrations.RunPython.noop),
    ]
