# Generated by Django 2.1.8 on 2019-04-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0023_auto_20190402_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperapplication',
            name='title',
            field=models.CharField(help_text='The title of your talk. Keep it short and catchy. 50 characters max. [Public]', max_length=255, verbose_name='Title'),
        ),
    ]
