# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='duration_hours',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='tickets_link',
            field=models.URLField(blank=True),
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='venue',
        ),
        migrations.AddField(
            model_name='workshop',
            name='extra_info',
            field=models.TextField(blank=True),
        ),
    ]
