# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 18:13
from __future__ import unicode_literals

from django.db import migrations, models


def populate_applicants(apps, schema_editor):
    Workshop = apps.get_model("workshops", "Workshop")
    for workshop in Workshop.objects.all():
        workshop.applicants.add(workshop.applicant)


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0017_auto_20170704_0833'),
        ('workshops', '0003_workshop_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='applicants',
            field=models.ManyToManyField(to='cfp.Applicant'),
        ),
        migrations.RunPython(populate_applicants),
        migrations.RemoveField(
            model_name='workshop',
            name='applicant',
        )
    ]
