# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_workshop_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='joindin_url',
            field=models.URLField(blank=True, help_text='URL to the event on JoindIn API.'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='rate_url',
            field=models.URLField(blank=True),
        ),
    ]
