# Generated by Django 2.0.4 on 2018-09-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_auto_20170924_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
