# Generated by Django 2.0.4 on 2018-09-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_workshop_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
