# Generated by Django 2.0.4 on 2018-05-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170606_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
    ]
