# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-04 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('diamond', 'Diamond Sponsor'), ('lanyard', 'Lanyard Sponsor'), ('track', 'Track Sponsor'), ('foodanddrinks', 'Food & Drinks Sponsor'), ('standard', 'Standard Sponsor'), ('supporter', 'Supporter Sponsor'), ('mainmedia', 'Main Media Sponsor'), ('media', 'Media sponsors'), ('video', 'Video sponsors')], default='standard', max_length=255)),
                ('about', models.TextField()),
                ('url', models.URLField(max_length=255)),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to='uploads/sponsors/')),
                ('is_active', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
