# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-04 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    replaces = [('sponsors', '0001_initial'), ('sponsors', '0002_auto_20150510_1350'), ('sponsors', '0003_sponsor_is_active'), ('sponsors', '0004_auto_20150512_1534'), ('sponsors', '0005_auto_20150521_0859'), ('sponsors', '0006_auto_20150914_1300'), ('sponsors', '0007_remove_sponsor_location'), ('sponsors', '0008_sponsor_order'), ('sponsors', '0009_auto_20170519_0944'), ('sponsors', '0010_auto_20170627_2001'), ('sponsors', '0011_auto_20170629_1208'), ('sponsors', '0012_auto_20170921_1332')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('diamond', 'Diamond Sponsor'), ('lanyard', 'Lanyard Sponsor'), ('track', 'Track Sponsor'), ('foodanddrinks', 'Food & Drinks Sponsor'), ('standard', 'Standard Sponsor'), ('supporter', 'Supporter Sponsor'), ('mainmedia', 'Main Media Sponsor'), ('media', 'Media sponsors'), ('video', 'Video sponsors')], default='standard', max_length=255)),
                ('about', tinymce.models.HTMLField()),
                ('url', models.URLField(max_length=255)),
                ('image', models.FileField(blank=True, max_length=255, null=True, upload_to='uploads/sponsors/')),
                ('is_active', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
