# Generated by Django 2.0.4 on 2018-04-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_squashed_0012_auto_20170921_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='about',
            field=models.TextField(),
        ),
    ]
