# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_vote_created_at'),
        ('voting', '0003_votetoken'),
    ]

    operations = [
    ]
