# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0017_auto_20170704_0833'),
        ('events', '0004_auto_20170516_1156'),
        ('voting', '0004_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_votes', to='cfp.PaperApplication')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_votes', to='events.Ticket')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='communityvote',
            unique_together=set([('ticket', 'application')]),
        ),
    ]
