# Generated by Django 2.0.4 on 2018-04-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_community_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='application',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='votetoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.DeleteModel(
            name='VoteToken',
        ),
    ]
