# Generated by Django 2.0.4 on 2018-04-05 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_joindin_url'),
        ('blog', '0003_post_is_sponsored'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='lead',
            field=models.TextField(blank=True),
        ),
    ]
