# Generated by Django 2.1.8 on 2019-05-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('bg_color', models.CharField(default='#000000', max_length=50)),
                ('fg_color', models.CharField(default='#FFFFFF', max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
