# Generated by Django 2.0.4 on 2018-04-21 12:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_squashed_0014_talk_joindin_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('average', models.FloatField()),
                ('distribution', django.contrib.postgres.fields.jsonb.JSONField()),
                ('talk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='talks.Talk')),
            ],
        ),
    ]
