# Generated by Django 2.1.7 on 2019-03-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0022_invite'),
        ('talks', '0002_surveyscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='applicants',
            field=models.ManyToManyField(to='cfp.Applicant'),
        ),
    ]
