# Generated by Django 2.1.7 on 2019-03-02 14:05

from django.db import migrations


def populate_applicants(apps, schema_editor):
    Talk = apps.get_model("talks", "Talk")
    for talk in Talk.objects.all():
        talk.applicants.add(talk.application.applicant)
        if talk.co_presenter:
            talk.applicants.add(talk.co_presenter)


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0003_talk_applicants'),
    ]

    operations = [
        migrations.RunPython(
            populate_applicants,
            migrations.RunPython.noop
        ),
    ]
