# Generated by Django 2.1.7 on 2019-03-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0004_talk_applicants_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='co_presenter',
        ),
    ]
