# Generated by Django 2.1.7 on 2019-04-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0005_remove_talk_co_presenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='duration',
            field=models.CharField(blank=True, choices=[('25', '25 Minutes'), ('45', '45 Minutes'), ('60', '60 Minutes')], max_length=255, null=True),
        ),
    ]
