# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0010_auto_20160910_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='duration',
            field=models.CharField(blank=True, choices=[('25', '25 Minutes'), ('45', '45 Minutes')], max_length=255, null=True),
        ),
    ]
